# Site settings
title: Siddharth Seth
email: siddharth.seth95@gmail.com
url: sidseth.me
description: "Here you can find basic information about me, Siddharth Seth. If you would like to get in touch, feel free to contact me. Thanks for your time!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Siddharth Seth 2015
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sidtheseth
  - title: facebook
    url: http://facebook.com/sidtheseth
  - title: linkedin
    url: http://linkedin.com/in/siddharthseth95
  - title: github
    url: http://github.com/siddharthseth

# Postal address (add as many lines as necessary)
address:
  - line: 2400 Durant Avenue
  - line: Ida Sproul #306
  - line: Berkeley, CA 94720

# Credits content
credits: 'This website was built by Siddharth Seth using Jekyll and the basic Freelancer theme.'

# Build settings
markdown: kramdown
permalink: pretty
